namespace CaixaDiario.API.Enums;

public enum CodigoRetorno
{
    SUCESSO,
    DADOS_INVALIDOS,
    CREDENCIAIS_INVALIDAS,
    USUARIO_INATIVO,
    TOKEN_INVALIDO,
    SEM_PERMISSAO,
    SENHA_MUITO_CURTA,
    USUARIO_NAO_ENCONTRADO,
    NOME_USUARIO_DUPLICADO,
    DATA_FUTURA,
    MOTIVO_OBRIGATORIO,
    REGISTRO_NAO_ENCONTRADO,
    ACESSO_NEGADO,
    ERRO_INTERNO
}
