// <auto-generated />
using System;
using CaixaDiario.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaixaDiario.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaixaDiario.API.Models.RegistroDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ContasPagar")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contas_pagar");

                    b.Property<string>("ContasReceber")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contas_receber");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<decimal>("Entrada")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("entrada");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("excluido");

                    b.Property<decimal>("Inicio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("inicio");

                    b.Property<string>("MotivoExclusao")
                        .HasColumnType("text")
                        .HasColumnName("motivo_exclusao");

                    b.Property<string>("Saidas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("saidas");

                    b.Property<decimal>("SaldoFinal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_final");

                    b.Property<DateTime>("SalvoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("salvo_em");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_atualizacao");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Data")
                        .IsUnique();

                    b.ToTable("registros_diarios", (string)null);
                });

            modelBuilder.Entity("CaixaDiario.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Loja")
                        .HasColumnType("text")
                        .HasColumnName("loja");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text")
                        .HasColumnName("usuario_atualizacao");

                    b.HasKey("Id");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("CaixaDiario.API.Models.RegistroDiario", b =>
                {
                    b.HasOne("CaixaDiario.API.Models.Usuario", "Cliente")
                        .WithMany("Registros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CaixaDiario.API.Models.Usuario", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
